site_name: challenge-question
site_url: https://goessl.github.io/challenge-question/
site_author: Sebastian Gössl
site_description: Challenge Question attempt progress.

repo_name: goessl/challenge-question
repo_url: https://github.com/goessl/challenge-question

copyright: Copyright &copy; 2026 Sebastian Gössl

theme:
  name: material
  features:
    - navigation.footer
  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to system preference

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_toc_entry: false
            show_symbol_type_heading: true
            members_order: source
            group_by_category: false
            docstring_style: numpy
            show_signature_annotations: true

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/goessl/
      name: goessl on Github
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/lordgoessl/
      name: lordgoessl on Instagram

markdown_extensions:
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.details
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true

extra_javascript:
  - mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

nav:
  - Home: index.md
  - challenge_question.md
  - challenge.md
  - immediate_deductions.md
  - single_particle.md
  - Any Wavefunctions:
    - any_wavefunctions/approach.md
    - any_wavefunctions/whole_solution_set.md
    - any_wavefunctions/explicit_construction.md
    - any_wavefunctions/counter_example.md
    - any_wavefunctions/discussion.md
    - any_wavefunctions\schroedinger.md
  - Going Vectorial:
    - going_vectorial/choosing_a_basis.md
    - Products:
      - going_vectorial/products/oh_look_a_polynomial.md
      - going_vectorial/products/series_representation_where_there_shouldnt_be_one.md
    - going_vectorial/roadmap.md
    - going_vectorial/degree_0.md
    - Degree 1:
      - going_vectorial/degree_1/full_occupation.md
      - going_vectorial/degree_1/explicit_example.md
    - Degree 2:
      - going_vectorial/degree_2/orthonormal_complement.md
      - going_vectorial/degree_2/explicit_example.md
    - Degree 3:
      - going_vectorial/degree_3/some_algebra.md
      - going_vectorial/degree_3/actually_degree_2_again_first.md
      - going_vectorial/degree_3/degree_3_-_almost_all_solutions.md
  - conventions.md
  - further_readings.md
  - package.md
